INSERT INTO `mydb`.`cartcheckout`
(`idcart_checkout`,
`firstNameBilling`,
`lastNameBilling`,
`mobileBilling`,
`emailBilling`,
`creditcard_type`,
`cartCheckoutStatus`,
`creditcard_url`,
`paymentReference`,
`datePurchased`,
`OrderCart_idOrderCart`,
`Coupon_idCoupon`)
VALUES
('1',
'Mandy',
'Brown',
'92924934',
'mandyBrown@gmail.com',
'VISA',
'VALID',
'www.visa.com',
'1232456',
'2022-02-15',
'1',
'1');

INSERT INTO `mydb`.`cartcheckout`
(`idcart_checkout`,
`firstNameBilling`,
`lastNameBilling`,
`mobileBilling`,
`emailBilling`,
`creditcard_type`,
`cartCheckoutStatus`,
`creditcard_url`,
`paymentReference`,
`datePurchased`,
`OrderCart_idOrderCart`,
`Coupon_idCoupon`)
VALUES
('2',
'Mandy',
'Brown',
'92924934',
'mandyBrown@gmail.com',
'VISA',
'VALID',
'www.visa.com',
'1232456',
'2021-02-15',
'3',
'2');

